"""Initial Migration

Revision ID: 6387dd1dfa17
Revises: e40910f07e34
Create Date: 2025-04-22 12:17:59.404192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '6387dd1dfa17'
down_revision: Union[str, None] = 'e40910f07e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('employee')]

    if 'role_id' not in existing_columns:
        op.add_column('employee', sa.Column('role_id', sa.String(length=30), nullable=True))
        op.create_unique_constraint(None, 'employee', ['role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_column('employee', 'role_id')
    # ### end Alembic commands ###
