"""added is_active cloumn to stages table

Revision ID: 672cbee002f6
Revises: 73fe7253e1df
Create Date: 2025-04-23 09:50:55.271855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '672cbee002f6'
down_revision: Union[str, None] = '73fe7253e1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # Fill existing NULLs before enforcing NOT NULL
    op.execute("UPDATE stages SET is_active = TRUE WHERE is_active IS NULL")
    
    op.alter_column('stages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
