"""expand_password_column_for_hash

Revision ID: d5e0f3c4ce68
Revises: 9c58e18de1cc
Create Date: 2026-05-21 14:16:33.697778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'd5e0f3c4ce68'
down_revision: Union[str, None] = '9c58e18de1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'role_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('employee', 'password',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('employee', 'role_id',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
